// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxD64CUOVFMRr2nMJcJk7el0OnPpg6VI0',
    appId: '1:240305059605:web:3bb1c82af0ab623927db1c',
    messagingSenderId: '240305059605',
    projectId: 'ai-assistant-service-d86f3',
    authDomain: 'ai-assistant-service-d86f3.firebaseapp.com',
    storageBucket: 'ai-assistant-service-d86f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJW18x7R1CKueaN5ZyHdplehGCpYKUL4',
    appId: '1:240305059605:android:6f094ec8170c6d6e27db1c',
    messagingSenderId: '240305059605',
    projectId: 'ai-assistant-service-d86f3',
    storageBucket: 'ai-assistant-service-d86f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA40o2iRRibUJ1sZVdPjd0JCTcZfR5vO_M',
    appId: '1:240305059605:ios:9f384d3795293a7427db1c',
    messagingSenderId: '240305059605',
    projectId: 'ai-assistant-service-d86f3',
    storageBucket: 'ai-assistant-service-d86f3.firebasestorage.app',
    iosBundleId: 'com.example.aiChatAssistant',
  );
}
